
CREATE OR REPLACE FUNCTION public.create_order(
  p_items jsonb,
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_address jsonb,
  p_payment_method text,
  p_coupon_code text DEFAULT NULL,
  p_user_id uuid DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_customer_id uuid;
  v_order_id uuid;
  v_order_code text;
  v_subtotal numeric := 0;
  v_discount numeric := 0;
  v_total numeric := 0;
  v_item jsonb;
  v_product record;
  v_coupon_result record;
BEGIN
  -- 1. Find or create customer
  IF p_user_id IS NOT NULL THEN
    SELECT id INTO v_customer_id FROM public.customers WHERE user_id = p_user_id;
  END IF;

  IF v_customer_id IS NULL THEN
    SELECT id INTO v_customer_id FROM public.customers
    WHERE email = lower(p_customer_email) AND user_id IS NULL
    LIMIT 1;
  END IF;

  IF v_customer_id IS NULL THEN
    INSERT INTO public.customers (name, email, phone, user_id)
    VALUES (p_customer_name, lower(p_customer_email), p_customer_phone, p_user_id)
    RETURNING id INTO v_customer_id;
  ELSE
    UPDATE public.customers
    SET name = p_customer_name, phone = p_customer_phone, updated_at = now()
    WHERE id = v_customer_id;
  END IF;

  -- 2. Calculate subtotal from server-side prices
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    SELECT id, name, price, sale_price, inventory_count
    INTO v_product
    FROM public.products
    WHERE id = (v_item->>'product_id')::uuid AND active = true;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Produto não encontrado: %', v_item->>'product_id';
    END IF;

    IF v_product.inventory_count < (v_item->>'qty')::int THEN
      RAISE EXCEPTION 'Estoque insuficiente para: %', v_product.name;
    END IF;

    v_subtotal := v_subtotal + (COALESCE(v_product.sale_price, v_product.price) * (v_item->>'qty')::int);
  END LOOP;

  -- 3. Validate coupon if provided
  IF p_coupon_code IS NOT NULL AND p_coupon_code <> '' THEN
    SELECT coupon_id, discount_value INTO v_coupon_result
    FROM public.validate_coupon(p_coupon_code, v_subtotal);

    IF FOUND THEN
      v_discount := v_coupon_result.discount_value;
      PERFORM public.increment_coupon_usage(v_coupon_result.coupon_id);
    END IF;
  END IF;

  v_total := v_subtotal - v_discount;
  IF v_total < 0 THEN v_total := 0; END IF;

  -- 4. Create order (order_code generated by trigger)
  INSERT INTO public.orders (
    order_code, customer_id, subtotal, discount, total,
    payment_method, shipping_address_snapshot, channel_origin
  ) VALUES (
    '', v_customer_id, v_subtotal, v_discount, v_total,
    p_payment_method, p_address, 'website'
  ) RETURNING id, order_code INTO v_order_id, v_order_code;

  -- 5. Insert order items and decrement inventory
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    SELECT id, name, price, sale_price INTO v_product
    FROM public.products WHERE id = (v_item->>'product_id')::uuid;

    INSERT INTO public.order_items (order_id, product_id, name_snapshot, unit_price, quantity, subtotal)
    VALUES (
      v_order_id,
      v_product.id,
      v_product.name,
      COALESCE(v_product.sale_price, v_product.price),
      (v_item->>'qty')::int,
      COALESCE(v_product.sale_price, v_product.price) * (v_item->>'qty')::int
    );

    PERFORM public.decrement_inventory(v_product.id, (v_item->>'qty')::int);
  END LOOP;

  -- 6. Return result
  RETURN jsonb_build_object(
    'order_id', v_order_id,
    'order_code', v_order_code,
    'subtotal', v_subtotal,
    'discount', v_discount,
    'total', v_total
  );
END;
$$;

-- Grant execute to anon and authenticated (guest + logged-in checkout)
GRANT EXECUTE ON FUNCTION public.create_order(jsonb, text, text, text, jsonb, text, text, uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.create_order(jsonb, text, text, text, jsonb, text, text, uuid) TO authenticated;
