
UPDATE products SET brand = 'Jequiti' WHERE sku = '99099965' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Jequiti' WHERE sku = '99019554' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Jequiti' WHERE sku = '99100421' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Jequiti' WHERE sku = '99100493' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '86603' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '89977' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'O Boticário' WHERE sku = '52172' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '93063' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-COOLGL-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-717SEXY-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-BELLMD-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-BELLMD-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-717SEXY-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-717ROSE-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-717ROSE-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-AFRODIT-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-COOLGL-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-AFRODIT-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-717MEN-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ANIMAL-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ANIMAL-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ATTRAC-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ATTRAC-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-BLUMEN-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ELATIO-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ELATIO-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-IADORR-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-IADORR-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-LAVIE-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-LAVIE-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-MRMILL-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-MRMILL-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-VICTOR-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-VICTOR-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-BLUMEN-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-BACCRT-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-CARLIS-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-CARLIS-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-CRDAVT-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-CRDAVT-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-DELINA-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-DELINA-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-NISHAN-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-SAVAGE-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-NISHAN-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-SAVAGE-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-SILVSC-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-SILVSC-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-TOBVAN-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-TOBVAN-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-YSAINT-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-YSAINT-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ARMAFN-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ASAD-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ASAD-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Lattafa' WHERE sku = 'PERF-BADOUD-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Lattafa' WHERE sku = 'PERF-BADOUD-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-FAKROS-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-FAKROS-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-KAYALI-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-KAYALI-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-MIGNON-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-MIGNON-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-SABAHW-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-SABAHW-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-SCNDAL-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-SCNDAL-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-YARA-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-YARA-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-CKONE-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-717NYC-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-717NYC-15' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-717MEN-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-ARMAFN-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-BACCRT-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '87303' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Naturall Mix' WHERE sku = 'PERF-CKONE-100' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'O Boticário' WHERE sku = '51236' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'O Boticário' WHERE sku = '55222' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'O Boticário' WHERE sku = '82688' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'O Boticário' WHERE sku = '48779' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '86226' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '47400' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'O Boticário' WHERE sku = '53835' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'O Boticário' WHERE sku = '85947' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '86538' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '88716' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '87340' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '89701' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '86227' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
UPDATE products SET brand = 'Eudora' WHERE sku = '86225' AND (brand IS NULL OR brand = '' OR brand ~ '^\s*$');
